org: matiasp1324
app: aws-lambda-crud-node
service: aws-lambda-crud-node

frameworkVersion: '3'

# en donde se subira la func
provider:
  name: aws
  runtime: nodejs14.x
  # region en donde es que estara
  region: us-west-2
# enrutador
functions:
  hello:
    handler: handler.hello
    events:
      - httApi:
          path: /
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
